image: maven:latest

clone:
  depth: full

pipelines:
  default:
    - step:
        name: Deploy to Heroku
        deployment: staging   # set to test, staging or production
        script:
          - mvn -B clean package # -B batch mode makes Maven less verbose
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD